export const CLEAR_INVOICE_NUMBER_FILTER = "CLEAR_INVOICE_NUMBER_FILTER";
export const CLEAR_MRR_FILTER = "CLEAR_MRR_FILTER";
export const CLEAR_TERM_LENGTH_FILTER = "CLEAR_TERM_LENGTH_FILTER";
export const SET_SELECTED_COLUMNS = "SET_SELECTED_COLUMNS";
export const SAVE_FILTER = "SAVE_FILTER";
export const UPDATE_FILTERED_DATA = "UPDATE_FILTERED_DATA";
